language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies

install: "pip install -r requirements.txt"
# command to run tests

# services setup

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create database travis_ci_test_1;' -U postgres

script: py.test --cov=lunatic test/

after_success:
  coveralls